flowchart TD
    A[Inicio do processo para a equipe] --> B["`**1. Carregamento dos dados** <BR> Equipes, OS tecnicas e comerciais`"]
    B --> C["`**2. Filtragem das OS validas**<br>Mesmo dia e datasol menor que inicio do turno`"]
    C --> D["`**3. Calculo da prioridade**<br>Prioridade, tempo de espera, violacao`"]
    D --> E["`**4. Metaheuristica Hibrida**<br>AG seleciona subconjunto`"]
    E --> F["`**5. SA refina solucao**`"]
    F --> G["`**6. ACO intensifica selecao final**`"]
    G --> H["`**7. Roteirizacao com VROOM**<br>Envio de jobs e obtencao da rota`"]
    H --> I{"`**VROOM respondeu?**`"}
    I -->|Sim| J["`**6. Calculo ETA e ETD pela rota VROOM**`"]
    I -->|Nao| K["`**Fallback OSRM**`"]
    K --> L{"`**OSRM respondeu?**`"}
    L -->|Sim| M["`**ETA e ETD via OSRM**`"]
    L -->|Nao| N["`**ETA e ETD via Haversine**`"]
    J --> O["`**7. Calculo do retorno a base**<br>Fim do turno estimado`"]
    M --> O
    N --> O
    O --> P["`**8. Resultado final**<br>OS selecionadas, tempos, distancia e equipe`"]
    classDef processo Sky stroke-width:2px, stroke-dasharray:none, stroke:#374D7C, fill:#E2EBFF, color:#374D7C;
    class A,B,C,D,E,F,G,H,J,K,M,N,O,P processo
    style I fill:#FFF3CD,stroke:#FFEEBA,stroke-width:2px
    style L fill:#FFF3CD,stroke:#FFEEBA,stroke-width:2px
    class I,L decisionmaking
    classDef decisionmaking fill:#FFF3CD,stroke:#FFEEBA,stroke-width:2px