curl -X POST "http://localhost:3000" \
-H "Content-Type: application/json" \
-d '{
  "vehicles":[{"id":0,"start":[-63.89,-8.76],"end":[-63.89,-8.76]}],
  "jobs":[{"id":1,"location":[-63.91,-8.74]},{"id":2,"location":[-63.85,-8.78]}]
}'
